// flow-typed signature: 37b418a0a513a3ad3e546e5c9fbba315
// flow-typed version: <<STUB>>/bestbuy_v^1.1.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bestbuy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bestbuy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bestbuy/bestbuy' {
  declare module.exports: any;
}

declare module 'bestbuy/examples/products' {
  declare module.exports: any;
}

declare module 'bestbuy/examples/recommendations' {
  declare module.exports: any;
}

declare module 'bestbuy/examples/stores' {
  declare module.exports: any;
}

declare module 'bestbuy/lib/AvailabilityStrategy' {
  declare module.exports: any;
}

declare module 'bestbuy/lib/DefaultStrategy' {
  declare module.exports: any;
}

declare module 'bestbuy/lib/index' {
  declare module.exports: any;
}

declare module 'bestbuy/lib/OpenBoxStrategy' {
  declare module.exports: any;
}

declare module 'bestbuy/lib/RecommendationsStrategy' {
  declare module.exports: any;
}

declare module 'bestbuy/lib/Resource' {
  declare module.exports: any;
}

declare module 'bestbuy/lib/WarrantiesStrategy' {
  declare module.exports: any;
}

declare module 'bestbuy/test/availability.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/bby.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/categories.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/defaultStrategy.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/lib/tape-nock-setup' {
  declare module.exports: any;
}

declare module 'bestbuy/test/openbox.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/products.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/recommendations.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/resourceStrategy.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/reviews.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/stores.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/useragent.test' {
  declare module.exports: any;
}

declare module 'bestbuy/test/warranties.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bestbuy/bestbuy.js' {
  declare module.exports: $Exports<'bestbuy/bestbuy'>;
}
declare module 'bestbuy/examples/products.js' {
  declare module.exports: $Exports<'bestbuy/examples/products'>;
}
declare module 'bestbuy/examples/recommendations.js' {
  declare module.exports: $Exports<'bestbuy/examples/recommendations'>;
}
declare module 'bestbuy/examples/stores.js' {
  declare module.exports: $Exports<'bestbuy/examples/stores'>;
}
declare module 'bestbuy/lib/AvailabilityStrategy.js' {
  declare module.exports: $Exports<'bestbuy/lib/AvailabilityStrategy'>;
}
declare module 'bestbuy/lib/DefaultStrategy.js' {
  declare module.exports: $Exports<'bestbuy/lib/DefaultStrategy'>;
}
declare module 'bestbuy/lib/index.js' {
  declare module.exports: $Exports<'bestbuy/lib/index'>;
}
declare module 'bestbuy/lib/OpenBoxStrategy.js' {
  declare module.exports: $Exports<'bestbuy/lib/OpenBoxStrategy'>;
}
declare module 'bestbuy/lib/RecommendationsStrategy.js' {
  declare module.exports: $Exports<'bestbuy/lib/RecommendationsStrategy'>;
}
declare module 'bestbuy/lib/Resource.js' {
  declare module.exports: $Exports<'bestbuy/lib/Resource'>;
}
declare module 'bestbuy/lib/WarrantiesStrategy.js' {
  declare module.exports: $Exports<'bestbuy/lib/WarrantiesStrategy'>;
}
declare module 'bestbuy/test/availability.test.js' {
  declare module.exports: $Exports<'bestbuy/test/availability.test'>;
}
declare module 'bestbuy/test/bby.test.js' {
  declare module.exports: $Exports<'bestbuy/test/bby.test'>;
}
declare module 'bestbuy/test/categories.test.js' {
  declare module.exports: $Exports<'bestbuy/test/categories.test'>;
}
declare module 'bestbuy/test/defaultStrategy.test.js' {
  declare module.exports: $Exports<'bestbuy/test/defaultStrategy.test'>;
}
declare module 'bestbuy/test/lib/tape-nock-setup.js' {
  declare module.exports: $Exports<'bestbuy/test/lib/tape-nock-setup'>;
}
declare module 'bestbuy/test/openbox.test.js' {
  declare module.exports: $Exports<'bestbuy/test/openbox.test'>;
}
declare module 'bestbuy/test/products.test.js' {
  declare module.exports: $Exports<'bestbuy/test/products.test'>;
}
declare module 'bestbuy/test/recommendations.test.js' {
  declare module.exports: $Exports<'bestbuy/test/recommendations.test'>;
}
declare module 'bestbuy/test/resourceStrategy.test.js' {
  declare module.exports: $Exports<'bestbuy/test/resourceStrategy.test'>;
}
declare module 'bestbuy/test/reviews.test.js' {
  declare module.exports: $Exports<'bestbuy/test/reviews.test'>;
}
declare module 'bestbuy/test/stores.test.js' {
  declare module.exports: $Exports<'bestbuy/test/stores.test'>;
}
declare module 'bestbuy/test/useragent.test.js' {
  declare module.exports: $Exports<'bestbuy/test/useragent.test'>;
}
declare module 'bestbuy/test/warranties.test.js' {
  declare module.exports: $Exports<'bestbuy/test/warranties.test'>;
}
