// flow-typed signature: 217ea41f5a57215d4e7cb5232573ba47
// flow-typed version: <<STUB>>/express-validator_v^3.2.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-validator/build/lib/express_validator' {
  declare module.exports: any;
}

declare module 'express-validator/build/lib/utils' {
  declare module.exports: any;
}

declare module 'express-validator/build/type-definition.spec' {
  declare module.exports: any;
}

declare module 'express-validator/build/typeDefinitionTest' {
  declare module.exports: any;
}

declare module 'express-validator/builtins' {
  declare module.exports: any;
}

declare module 'express-validator/lib/express_validator' {
  declare module.exports: any;
}

declare module 'express-validator/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-validator/build/lib/express_validator.js' {
  declare module.exports: $Exports<'express-validator/build/lib/express_validator'>;
}
declare module 'express-validator/build/lib/utils.js' {
  declare module.exports: $Exports<'express-validator/build/lib/utils'>;
}
declare module 'express-validator/build/type-definition.spec.js' {
  declare module.exports: $Exports<'express-validator/build/type-definition.spec'>;
}
declare module 'express-validator/build/typeDefinitionTest.js' {
  declare module.exports: $Exports<'express-validator/build/typeDefinitionTest'>;
}
declare module 'express-validator/builtins.js' {
  declare module.exports: $Exports<'express-validator/builtins'>;
}
declare module 'express-validator/index' {
  declare module.exports: $Exports<'express-validator'>;
}
declare module 'express-validator/index.js' {
  declare module.exports: $Exports<'express-validator'>;
}
declare module 'express-validator/lib/express_validator.js' {
  declare module.exports: $Exports<'express-validator/lib/express_validator'>;
}
declare module 'express-validator/lib/utils.js' {
  declare module.exports: $Exports<'express-validator/lib/utils'>;
}
